export default {
    "Thunderstorm": "⛈️",
    "Drizzle": "🌧️",
    "Rain": "🌧️",
    "Snow": "🌨️",
    "Mist": "🌫️",
    "Smoke": "🌫️",
    "Haze": "🌫️",
    "Dust": "🌫️",
    "Fog": "🌫️",
    "Sand": "🌫️",
    "Ash": "🌫️",
    "Squall": "🌫️",
    "Tornado": "🌪️",
    "Clear": "☀️",
    "Clouds": "⛅",
}